# list of words for a hangman game.
#using a tuple because indexing and random attributes
words =  ("alligator", "alpaca", "ant", "antelope", "ape", "armadillo", "baboon", "badger",
    "bat", "bear", "beaver", "bee", "bison", "boar", "buffalo", "butterfly",
    "camel", "cat", "caterpillar", "cheetah", "chicken", "chimpanzee", "chinchilla", "clam",
    "cobra", "crab", "crane", "crocodile", "crow", "deer", "dinosaur", "dog",
    "dolphin", "donkey", "dove", "dragonfly", "duck", "eagle", "eel", "elephant",
    "elk", "emu", "falcon", "ferret", "finch", "fish", "flamingo", "fly",
    "fox", "frog", "gazelle", "gerbil", "giraffe", "gnat", "goat", "goose",
    "gorilla", "grasshopper", "gull", "hamster", "hare", "hawk", "hedgehog", "heron",
    "herring", "hippopotamus", "hornet", "horse", "human", "hummingbird", "hyena", "ibis",
    "iguana", "jackal", "jaguar", "jellyfish", "kangaroo", "kinkajou", "koala", "komodo dragon",
    "kookaburra", "lemur", "leopard", "lion", "llama", "lobster", "locust", "lynx",
    "macaw", "magpie", "mallard", "manatee", "mandrill", "mink", "mole", "mongoose",
    "monkey", "moose", "mosquito", "moth", "mouse", "mule", "narwhal", "newt",
    "nightingale", "octopus", "okapi", "opossum", "ostrich", "otter", "owl", "ox",
    "oyster", "panda", "panther", "parrot", "partridge", "peacock", "pelican", "penguin",
    "pheasant", "pig", "pigeon", "platypus", "polar bear", "porcupine", "porpoise", "quail",
    "quetzal", "rabbit", "raccoon", "ram", "rat", "raven", "reindeer", "rhinoceros",
    "rook", "salamander", "salmon", "sandpiper", "sardine", "scorpion", "seahorse", "seal",
    "shark", "sheep", "shrew", "shrimp", "skunk", "sloth", "snail", "snake",
    "sparrow", "spider", "squid", "squirrel", "starling", "stingray", "stork", "swan",
    "tapir", "tarsier", "termite", "tiger", "toad", "toucan", "trout", "turkey",
    "turtle", "vicuna", "viper", "vulture", "wallaby", "walrus", "wasp", "weasel",
    "whale", "wolverine", "wombat", "woodpecker", "worm", "wren", "yak", "zebra")
